{
  parserClass="org.intellij.sdk.DotStudy.Language.parser.SimpleParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Simple"
  psiImplClassSuffix="Impl"
  psiPackage="org.intellij.sdk.DotStudy.Language.psi"
  psiImplPackage="org.intellij.sdk.DotStudy.Language.psi.impl"

  elementTypeHolderClass="org.intellij.sdk.DotStudy.Language.psi.SimpleTypes"
  elementTypeClass="org.intellij.sdk.DotStudy.Language.psi.SimpleElementType"
  tokenTypeClass="org.intellij.sdk.DotStudy.Language.psi.SimpleTokenType"
}

simpleFile ::= item_*

private item_ ::= (property|TITLE|SUBTITLE|LINK|CRLF)

//property ::= (KEY SEPARATOR VALUE)
property ::= (KEY SEPARATOR (VALUE VALUE_SEPARATOR)*)
//answer ::= (CRLF LIST_SEPARATOR)? (VALUE VALUE_SEPARATOR)
